### ISSUE TITLE
Preview PR

### ISSUE THREAD

**Issue by davidak** [wesbos/awesome-uses#1021]
I missed this typo in the review, so i had to do an emergency fix and push to master directly.

![Screenshot from 2020-11-01 21-09-21](https://user-images.githubusercontent.com/91113/97813299-79873980-1c87-11eb-9236-656236066b16.png)

It would be easier to notice when a preview would be generated for every PR.

I don't know how the deployment works. When it's netlify, i know it's possible since we have it NixOS https://github.com/NixOS/nixos-homepage/pull/634/checks?check_run_id=1317935126 but only for local branches from members, because the deployment job could reveal secrets. There might be a solution to create previews for PRs.

**Comment by HugoDF** [comment]
Each PR is deployed to Netlify, you can access it by clicking "Details" on the `deploy/netlify` GitHub status.

![Screenshot 2020-11-15 at 19 19 13](https://user-images.githubusercontent.com/6459679/99194484-8c196c80-2777-11eb-9dc2-6a8b58ce8089.png)

**Comment by davidak** [comment]
Perfect. That solves it for me.
