### ISSUE TITLE
Migration Help Needed

### ISSUE THREAD

**Issue by wesbos** [wesbos/awesome-uses#117]
https://github.com/wesbos/awesome-uses/blob/website/migration.md

We need to move these people over to the data.js file:

Grab a random person, and fill out the info as best as possible.

If possible maybe ask the user on twitter to update or review theirs.

When done, check that person off.

**Comment by HugoDF** [comment]
Latest migration file is actually https://github.com/wesbos/awesome-uses/blob/master/migration.md
