### ISSUE TITLE
Making sure all countries are visible for filtering option by nation at top 

### ISSUE THREAD

**Issue by jai-dewani** [wesbos/awesome-uses#1234]
There are already a lot of countries on this list but also a lot of them are still missing, I think there should be an automated way to add all the countries for which we have an entry in our list. 

![image](https://user-images.githubusercontent.com/33520257/132524500-29f9a79c-83c7-4016-b9c1-73d436d85520.png)

**Comment by wesbos** [comment]
Hey, the countries will pop up once there are people with entires that live in that country. It's dynamically added
