### ISSUE TITLE
Delist Sami Singh

### ISSUE THREAD

**Issue by r8u** [wesbos/awesome-uses#1346]
I suggest you delist Sami Singh, his website contains Swastikas as can be seen [here](https://httpster.io/article/2021-07-02-test-post/)

**Comment by BlakeCampbells** [comment]
Whoa, good call-out. I'll remove him shortly.

**Comment by BlakeCampbells** [comment]
Removed him, thanks for letting me know.

See: https://github.com/wesbos/awesome-uses/pull/1347
