### ISSUE TITLE
Reject PR if invalid data

### ISSUE THREAD

**Issue by wesbos** [wesbos/awesome-uses#141]
Need some way to reject the PR if the submitted data doesn't meet the shape and requirements of what we want.

Maybe convert to Typescript? 

Or can we do it with with PropTypes? 

Seems like a good use case for github actions

**Comment by HugoDF** [comment]
@wesbos couldn't this be achieved with schema validation of data.js? Using something like Joi

**Comment by wesbos** [comment]
Ohh - I have never done this. Looks exactly what I want!

**Comment by iamandrewluca** [comment]
Github Action that validates data.js using a schema.

**Comment by HugoDF** [comment]
@iamandrewluca not sure I understand what difference it would make.

In any case the current schema for each person is:

```
{
  name: String,
  description: String,
  url: String,
  twitter: String (optional?),
  emoji: String (optional?),
  country: String,
  computer: String (Enum('apple', 'windows', 'linux')?),
  phone: String (Enum('iphone', 'android')?),
  tags: Array(String),
} 
```

Technically we could use TypeScript, try to compile `data.ts`, which would fail if the static data doesn't match the interface for the `pages` array.

Or as mentioned, using schema validation library, wrapped as a script that exits with 0 (sucess) or 1 (error).
```js
import pages from './data.js'
const schema = {};

if (validate(pages, schema)) {
  process.exit(0)
} else {
  process.exit(1)
}
```

**Comment by wesbos** [comment]
Keep it as .js - no one likes writing JSON by hand :)

**Comment by HugoDF** [comment]
I've just had another dig around.

There seems to be a validation library that looks like React PropTypes but for JS objects: https://github.com/eliot-akira/proptypes-schema

Joi (https://github.com/hapijs/joi) has a pretty big market share in terms of validation library but it's a pretty chunky dependency.

If we can decide on which library and confirm that the schema above is correct, I think the implementation is pretty trivial.

**Comment by iamandrewluca** [comment]
I would recommend https://github.com/epoberezkin/ajv

**Comment by wesbos** [comment]
AJV seems to be for JSON.

Let's use joi

**Comment by WretchedDade** [comment]
Just to add my 2 cents. I've used https://github.com/jquense/yup before!

**Comment by iamandrewluca** [comment]
Ok, pages can be validated using ajv because they can be stringified
Here is a json schema

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "/uses schema validation",
  "type": "array",
  "items": { "$ref": "#/definitions/page" },
  "definitions": {
    "page": {
      "type": "object",
      "properties": {
        "name": { "type": "string" },
        "description": { "type": "string" },
        "url": { "type": "string" },
        "twitter": { "type": "string" },
        "emoji": { "type": "string" },
        "country": { "type": "string" },
        "computer": {
          "type": "string",
          "enum": ["apple", "windows", "linux"]
        },
        "phone": {
          "type": "string",
          "enum": ["ios", "iphone", "android"]
        },
        "tags": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "additionalProperties": false,
      "required": [
        "name",
        "description",
        "url",
        "country"
      ]
    }
  }
}
```
