### ISSUE TITLE
Image loading CDN 404s

### ISSUE THREAD

**Issue by Hacksore** [wesbos/awesome-uses#1558]
Hi Folks! I wanted to start this discussion to talk about the 3 dimensions about how images are served 😅. 

I saw many failures on the CDN today so figured it might be worth discussing options to solve this.

```
Dimension 1: images.weserv.nl (which this is more of a CDN for both the image and fallback)
Dimension 2: unavatar.io/Hacksore
Dimension 3: unavatar.io/boult.me&w=100&l=9&af&il&n=-1
```

Errors seeen
```
GET https://images.weserv.nl/?url=https://unavatar.io/MRebehn?fallback=https://unavatar.io/mattaz.com&w=100&l=9&af&il&n=-1 404
GET https://images.weserv.nl/?url=https://unavatar.io/kmorope?fallback=https://unavatar.io/camiloromero.dev&w=100&l=9&af&il&n=-1 404
GET https://images.weserv.nl/?url=https://unavatar.io/trovster?fallback=https://unavatar.io/www.trovster.com&w=100&l=9&af&il&n=-1 404
GET https://images.weserv.nl/?url=https://unavatar.io/BenDMyers?fallback=https://unavatar.io/benmyers.dev&w=100&l=9&af&il&n=-1 404
```

**Comment by wesbos** [comment]
hmmm yeah

The URL stack is actually:

Dimension 1: images.weserv.nl?url=XXX&w=100&l=9&af&il&n=-1
Dimension 2: unavatar.io/Hacksore
Dimension 3: unavatar.io/boult.me

Unavatar made the twitter images paid, so that is why the quality has gone down.

I think the issue is that the weserv.nl url isn't falling back

Broken:

https://images.weserv.nl/?url=https://unavatar.io/MRebehn?fallback=https://unavatar.io/mattaz.com

Working:

https://unavatar.io/MRebehn?fallback=https://unavatar.io/mattaz.com


Perhaps it's a URL encoding issue?

**Comment by Hacksore** [comment]
Can we just hotlink Github avatars 😬?

**Comment by wesbos** [comment]
Half tempted to write a scraper that would render twitter and get the profile image..

**Comment by Hacksore** [comment]
I'd say a long term solution would be to require the Github user id with the data object?

Then we can hotlink their image:
`https://avatars.githubusercontent.com/u/<userId>?s=80`

However, this makes it hard to go and fix all existing users. Maybe it could just be a manual one time migration effort (automation might be not worth it in this case)?

**Comment by wesbos** [comment]
Yeah it would have to be automatic, espeically because asking people what their github ID is isn't ideal. 

I wonder if it could be found from the git blame?

**Comment by Hacksore** [comment]
I mean there are some places where people did a format overwriting the contributor so I don't think that's gonna work sadly. 

Could be wrong though and we need some elaborate script 😅.

**Comment by wesbos** [comment]
It is now - had some issues with the deploy. All fixed

**Comment by wesbos** [comment]
I've switched to just using unavatar without the `images.weserv.nl` - seems like they take a bit to generate on first call, but once they are in the unavatar cache, everything is fast and were getting about 98% hit rate.

**Comment by wesbos** [comment]
oop never mind

<img width="781" alt="Screenshot 2023-04-14 at 9 54 51 AM" src="https://user-images.githubusercontent.com/176013/232063951-81a07552-0e68-4022-8984-9df0be5e0dc3.png">

**Comment by Hacksore** [comment]
Since we have a fallback now I am going to close this out 😬. 

If there is a more long term solution will likely have to be handled by @wesbos.
