### ISSUE TITLE
The site is down ATM

### ISSUE THREAD

**Issue by spersico** [wesbos/awesome-uses#1575]
Gonna be honest, was looking for codes for the giveaway, and checking Wes' code, and got to know this repo.

But the site is down, just so you know
<img width="423" alt="image" src="https://user-images.githubusercontent.com/10502605/231831059-fb74b927-52a9-4edc-b82c-294e901233c4.png">

<img width="494" alt="Screenshot 2023-04-13 at 13 57 40" src="https://user-images.githubusercontent.com/10502605/231831553-a578ecce-5246-4a69-8fdc-af10284d4135.png">

**Comment by wesbos** [comment]
hmmm. - taking a look now

**Comment by bushblade** [comment]
Been down all day for me too.
If it helps, this is what I see
![Screenshot_2023-04-13_18-29-54](https://user-images.githubusercontent.com/21976188/231838553-804769a8-4d91-4db8-9d08-cc46eaa8bdc2.png)

The ID changes on a refresh.

**Comment by spersico** [comment]
Just an update: it started working for a couple of minutes (just now), and I just reloaded again, and it was broke again 😓

**Comment by wesbos** [comment]
Got it figured out! https://github.com/wesbos/awesome-uses/blame/cdf50e09ec056b5fa2c0f51a5ffb84f2370737c4/server.ts#L18 

This line was ignoring everything from the build? @BlakeCampbells I know you did this to upgrade the node version. What was that last line for, if you remeber? I commented it out and we're back in business

**Comment by BlakeCampbells** [comment]
I was updating the regex for the assets because it was failing with the new node version. Thanks for fixing it!  🙌
<img width="972" alt="Screen Shot 2023-04-13 at 7 44 26 PM" src="https://user-images.githubusercontent.com/6901655/231905911-286720c2-a9e3-44f1-b27f-cc1a344e4078.png">
@wesbos

**Comment by wesbos** [comment]
Gotcha! I think me removing the last one stops the .js files from being served by the netlify CDN, and instead serves them up via the edge function. Ill fix that - thanks @BlakeCampbells!
