### ISSUE TITLE
Trim or ellipse long urls 

### ISSUE THREAD

**Issue by brohlson** [wesbos/awesome-uses#206]
Causing some UI issues 

![Screen Shot 2020-01-09 at 12 18 25 PM](https://user-images.githubusercontent.com/18178678/72101804-6bbc8e00-32da-11ea-92ff-6d1365f2678c.png)

**Comment by WestBrian** [comment]
Looks like someone submitted a fix #232

**Comment by brohlson** [comment]
Closed in favor of #232
