### ISSUE TITLE
Count, display, and validation issues with regional flags

### ISSUE THREAD

**Issue by clarkeash** [wesbos/awesome-uses#278]
The count next to 🏴󠁧󠁢󠁥󠁮󠁧󠁿says 3, but 2 people are displayed.

The filter says null:
```
<label for="filter-null" class="Topics__Tag-sc-80i8eu-1 bFdvcV">
    <input type="radio" name="tag" id="filter-null" value="🏴󠁧󠁢󠁥󠁮󠁧󠁿">
    <span class="Topics__TagEmoji-sc-80i8eu-2 iNCQMW">🏴󠁧󠁢󠁥󠁮󠁧󠁿</span>
    <span class="Topics__TagCount-sc-80i8eu-3 kqfjcM">3</span>
</label>
```

**Comment by wesbos** [comment]
I noticed this with a few other - columbia too. 

Anyone want to take a dive into why? It's in the stat.js gatsby-node.js files where the counting is done

**Comment by wesbos** [comment]
This has something to do with 🏴 being two emojis?

**Comment by christianhg** [comment]
Perhaps it's a bug in the `country-emoji` library. For the english flag, it returns `undefined` when I test it on https://npm.runkit.com/country-emoji:

<img width="624" alt="Screen Shot 2020-01-10 at 20 48 44" src="https://user-images.githubusercontent.com/4602382/72181981-cb09c380-33ea-11ea-96c1-0b5906c876c2.png">

**Comment by MichaelE1** [comment]
`country-emoji` unfortunately doesn't support regional flags (e.g. England, Scotland and Wales). Regional flags are represented differently in unicode. [This](https://github.com/meeDamian/country-emoji/blob/master/countries.json) shows the list of countries supported.

Unless it's changed recently, I don't think windows 10 has any support for displaying flags (at least by default).

**Comment by sam-cross** [comment]
@MichaelE1 spot on. All I see for country flags are letters. 
![image](https://user-images.githubusercontent.com/6699307/72205937-64cf8000-3480-11ea-9b0d-788c4b1d9c32.png)

Still doesn't explain the black flag issue though. Unless that isn't actually a black flag... 
![image](https://user-images.githubusercontent.com/6699307/72205956-9ea08680-3480-11ea-9c72-380745477278.png)

**Comment by clarkeash** [comment]
@sam-cross sorry, I probably shouldn't have used the flag in the title. It's the England flag.
![Screenshot 2020-01-13 at 16 52 36](https://user-images.githubusercontent.com/1612186/72270229-23c4a080-3625-11ea-86ff-c3e6bb2ccde6.png)

I am not sure how many countries have regional flags but for England, we could just replace it with the UK flag

**Comment by sam-cross** [comment]
@clarkeash huh, weird that it just switches it to a plain black flag instead of the "GB" country code then. Even when I copied-and-pasted it, it copied the black flag.

**Comment by clarkeash** [comment]
I copy & pasted the same flag and in some places it black and in others its correct:
![Screenshot 2020-01-14 at 11 32 50](https://user-images.githubusercontent.com/1612186/72336740-a864fc80-36c1-11ea-836d-aaf09158ff65.png)

**Comment by sam-cross** [comment]
I think we should use [ISO 3166 Alpha-2 codes](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes) instead. This would make it easier for users to add their country codes and it would be super simple to convert existing flags to these.

Then, the conversion from country code to flag could be done on front-end.

**Comment by wesbos** [comment]
I'm not sure people know what their country code is. I say we leave it as emojis right now and just address the issues as they pop up..
