### ISSUE TITLE
Add GitHub URL support

### ISSUE THREAD

**Issue by sam-cross** [wesbos/awesome-uses#328]
Seeing as this is hosted on GitHub already, it would be a nice addition to have GitHub links alongside Twitter links. Maybe save some people a click.

Example:

![image](https://user-images.githubusercontent.com/6699307/72206111-ea9ffb00-3481-11ea-9e83-5a92ec608c86.png)

Just a thought 🥚

**Comment by wesbos** [comment]
Thanks - not sure if I want to go down this route  - as then we will need to start adding every link under the sun. Will think about it..
