### ISSUE TITLE
Short description of users? 

### ISSUE THREAD

**Issue by dragGH102** [wesbos/awesome-uses#33]
I've seen a similarly repository just last week.

But... web developer, marketer etc. don't really tell much. One has to open each and every link to understand the orientation of the content. 

è. g. web developer specialized in X? 
marketer on ethical marketing? SEO? content strategy? 

and so on...

**Comment by ahinkle** [comment]
Yeah, I agree. It would be nice to know what type of developer they specialize in.. 

Personally, I'm a Laravel/Vue developer and it would be nice to see how other Laravel or Vue developers work without having to sift through a bunch of non-sense.

**Comment by wesbos** [comment]
Adding it now - add yourself! 

https://github.com/wesbos/awesome-uses/blob/website/src/data.js
