### ISSUE TITLE
Images are not being displayed

### ISSUE THREAD

**Issue by ThomasLarge** [wesbos/awesome-uses#347]
No sure if it's a config thing but there's some display pictures that are not coming though?

**Comment by wesbos** [comment]
We use the clearbit logo API. 

His is because people don't have a logo meta on their site. More info on how to add here: https://clearbit.com/logo

**Comment by fylzero** [comment]
@wesbos I didn't have a logo when I submitted my site...  I've since updated the necessary meta data, still no logo shows for my site or via ClearBit.  Do I need to resubmit?
