### ISSUE TITLE
Standardize /uses pages for aggergation

### ISSUE THREAD

**Issue by BryanSchuetz** [wesbos/awesome-uses#365]
Feature Request: I was just thinking, it's a shame that the /uses pages aren't standardized. First thing I wanted to do was to crawl everyone's pages to see what percent are using Sublime, VS Code, Atom, etc.

I suppose I could try and scrape, but that's a giant PIA. Would be nicer, and scale better if there was an agreed upon JSON format or something.

**Comment by wesbos** [comment]
Thanks a ton - I very much like this idea, but I certainly don't want to be in charge of something like this... 

anyone else have thoughts? I just wanted this to be a fun website :)

**Comment by davidosomething** [comment]
vote nay, it should be an expression of creativity with loose guidelines
also not everyone will fit in the guidelines (not everyone is a dev or just talking about their dev work)

**Comment by wesbos** [comment]
Yeah - my thoughts exactly. Something nice about just having a page with text on it and not over complicating it.
