### ISSUE TITLE
Image graceful fallback

### ISSUE THREAD

**Issue by fylzero** [wesbos/awesome-uses#369]
Since the images are pulled from site meta data, it seems "broken" to display broken images.

I'd like to suggest having a more graceful fallback placeholder image and add instructions for what meta data is referenced in the submission instructions.

**Comment by HugoDF** [comment]
Related MR https://github.com/wesbos/awesome-uses/pull/340

**Comment by HugoDF** [comment]
Current state for this issue

- https://github.com/wesbos/awesome-uses/pull/379 solves the fallback issue by using unavatar, **but** unavatar doesn't support passing a size parameter so we would regress on https://github.com/wesbos/awesome-uses/pull/338
- https://github.com/wesbos/awesome-uses/pull/340 tries to implement a React + SVG asset fallback solution but doesn't work (needs to be investigated)

**Comment by fylzero** [comment]
@HugoDF Much better!  Thanks!
