### ISSUE TITLE
Adapt validation action to take into consideration only added persons

### ISSUE THREAD

**Issue by iamandrewluca** [wesbos/awesome-uses#382]

**Comment by HugoDF** [comment]
@iamandrewluca this will entail some git-foo I think

I dunno how I feel about not checking that URLs still exist (eg. someone deletes their "uses" page) unless being on uses.tech means that _at some point_ you had a "uses" page

**Comment by iamandrewluca** [comment]
> this will entail some git-foo I think
yes, I'll take care of this.

> I dunno how I feel about not checking that URLs still exist
we can create an action that will run on a schedule to check for all urls

**Comment by HugoDF** [comment]
nice one!
