### ISSUE TITLE
Feature: Add CSS for a:visited on the displayed Name

### ISSUE THREAD

**Issue by fylzero** [wesbos/awesome-uses#391]
Feature Request

I'd like to request to add CSS for a:visited on the h3 tag where the person's name is displayed ...maybe a traditional purple?  #b066ff

Reason being, this list is growing and it would be nice to be able to visualize what has been visited already vs what hasn't been viewed yet.

**Comment by HugoDF** [comment]
I can have a crack at this if we've agreed the use of `#b066ff` 😄  unless @fylzero you want to pick it up?

**Comment by fylzero** [comment]
@HugoDF Please do.  I was struggling to figure out where to make this change, otherwise I would have submitted a PR.  😟

**Comment by HugoDF** [comment]
@fylzero feel free to have a look at the code

**Comment by fylzero** [comment]
@HugoDF I've pulled the project...  can't figure out where css/scss lives?

**Comment by HugoDF** [comment]
@fylzero this PR has the changes https://github.com/wesbos/awesome-uses/pull/436

The CSS is in 2 main spots, `src/components/layout.js` (setting CSS variables) and in the components themselves with styled-components.

**Comment by fylzero** [comment]
@HugoDF Sorry, I live in Laravel/Vue land for the most part.  Not used to finding css in js files.  😄

**Comment by fylzero** [comment]
@HugoDF Thanks for putting that together!  That'll be a helpful improvement I think.
