### ISSUE TITLE
Find a way for user to add their data without modifing data.js directly

### ISSUE THREAD

**Issue by iamandrewluca** [wesbos/awesome-uses#410]

**Comment by wesbos** [comment]
I think now that the landslide of people have been added in, it should be fine. Plus the comment at the end of data.js 🤣

**Comment by iamandrewluca** [comment]
🙂 Ok, agree, I'll close it for now then

**Comment by wesbos** [comment]
Oh and I know a lot of n00bs accidentally break the entire thing, or delete someone else, or re-indent the entire thing. I kind of like that - this is a low stakes way to get involved with git and I've already heard from a few people that adding themselves was a great way to learn :)
