### ISSUE TITLE
Country count growing exponentially

### ISSUE THREAD

**Issue by vpicone** [wesbos/awesome-uses#440]

**Comment by iamandrewluca** [comment]
Think the issue is here

https://github.com/wesbos/awesome-uses/blob/b7c00c0cd1b691752ae7841e24b4a8a1d20df258/src/util/stats.js#L24

Should be
```js
acc[country.name].count += 1;
```

**Comment by vpicone** [comment]
@iamandrewluca dang beat me to it haha
