### ISSUE TITLE
Feature: comment on PR with validation output

### ISSUE THREAD

**Issue by HugoDF** [wesbos/awesome-uses#478]
It seems possible to leave a comment on PRs when validation fails.

See  https://github.com/unsplash/comment-on-pr, code is obviously Ruby but equivalent functionality in JS should do the trick.

**Comment by sam-cross** [comment]
This would be SO helpful. Might look into this tonight.

**Comment by HugoDF** [comment]
Even better would be to take a screenshot/photo of the uses page being submitted so we don't have to open the URLs to review that it's not a placeholder.

**Comment by wesbos** [comment]
👍🏻 would love this feature for commenting what went wrong

**Comment by HugoDF** [comment]
I'm happy to have a stab at this later today.

**Comment by sam-cross** [comment]
Please do - I tried looking into it but I have no idea how to use GitHub Actions. I did find [this](https://github.com/thollander/actions-comment-pull-request/blob/master/src/main.ts) which might be useful!

**Comment by HugoDF** [comment]
Nice one, I think using pageres + the examples in here we should be able to get this over the line.

**Comment by HugoDF** [comment]
@wesbos @sam-cross PR is up and working

I might publish it as a standalone GitHub action "Leave PR comment"

**Comment by HugoDF** [comment]
I believe since we're integrating more tightly with GitHub, we could also validate that the PR name is formatted as expected & that the PR template has been filled out.

**Comment by HugoDF** [comment]
Interesting, the commenting doesn't  work, probably due to user permissions. We might need to generate another token & use that instead of the default one.

**Comment by sam-cross** [comment]
@HugoDF re PR validation - this would be a good idea, especially titles.

**Comment by iamandrewluca** [comment]
@HugoDF 
> We might need to generate another token

https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token#about-the-github_token-secret

**Comment by HugoDF** [comment]
@iamandrewluca

> If you need a token that requires permissions that aren't available in the GITHUB_TOKEN, you can create a personal access token and set it as a secret in your repository

I believe the issue is with PR or comment access on forked repositories.

**Comment by iamandrewluca** [comment]
That means that if you need more permissions that it offers `GITHUB_TOKEN`,  you should create your own.

**Comment by HugoDF** [comment]
I agree, will sort out later today 👍.

In the meantime, the validation check is still working as expected, just no comments unless a maintainer opened the PR.

**Comment by iamandrewluca** [comment]
Some references:
- https://github.com/actions/toolkit/tree/master/packages/github
- https://octokit.github.io/rest.js/#octokit-routes-pulls-create-comment

**Comment by iamandrewluca** [comment]
I think you a right based on forked repo.

When action is run on a PR from a fork, The `GITHUB_TOKEN` will have only read acce, for that PR.
And I think we can't fix this for now, because of security reasons.

**Comment by iamandrewluca** [comment]
You mean to run cron on master, and comment on PR's that are open?

**Comment by HugoDF** [comment]
Yep

**Comment by rohit-gohri** [comment]
Instead of implementing your own implementation for commenting and validation scripts, you could use the tried and tested DangerJS: https://danger.systems/js/

It is also available as an action, Github Repo: https://github.com/danger/danger-js/

It is made exactly for validating common things in PRs, and it provides lots of utils to help out with that including posting comments, getting branch name, github API access, git diffs. 

If this seems like a good idea then I could open up a PR implementing existing validation script with it.

**Comment by HugoDF** [comment]
@rohit-gohri go for it

**Comment by rohit-gohri** [comment]
DangerJS would also need a Personal Access Token: https://danger.systems/js/guides/getting_started.html#creating-a-bot-account-for-danger-to-use. 
Though it can be from any Bot user, and that does not need to be given access to the repo. 

So, ideally a token for a bot account with access to no repos, with just the 'public_repos' scope. If that can be added as `DANGER_GITHUB_API_TOKEN` in the secrets I would be able to finish the PR.

**Comment by HugoDF** [comment]
Good one @rohit-gohri 

I don't have access to secrets I don't think so we'll have to leave it with @wesbos

**Comment by rohit-gohri** [comment]
@wesbos it'd be great if you could add a PAT as a secret. Just a reminder.

> DangerJS would also need a Personal Access Token: [danger.systems/js/guides/getting_started.html#creating-a-bot-account-for-danger-to-use](https://danger.systems/js/guides/getting_started.html#creating-a-bot-account-for-danger-to-use).
> Though it can be from any Bot user, and that does not need to be given access to the repo.
> 
> So, ideally a token for a bot account with access to no repos, with just the 'public_repos' scope. If that can be added as `DANGER_GITHUB_API_TOKEN` in the secrets I would be able to finish the PR.

**Comment by rohit-gohri** [comment]
@wesbos It'd be great if you could take a look at #796. Validation comments would look like this after it: 



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>There are 1 failing URL(s)</td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>There are 1 validation error(s)</td>
    </tr>
  </tbody>
</table>



### Failing URLs
- URL, https://rohit.page/using, failed with status code: 404

### Validation Issues
- Rohit Gohri: "twitter" with value "@rohit-gohri" fails to match the required pattern: /^@?(\w){1,15}$/
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against c1c356e6229f511fc684eb30ba08c664c680eae2
</p>

 
Just need to add a personal access token of a dummy account to the repo with env var `DANGER_GITHUB_API_TOKEN`

**Comment by rohit-gohri** [comment]
#796 was merged but since there is no DANGER_GITHUB_API_TOKEN in the secrets all the builds are failing 🙈
