### ISSUE TITLE
What is the best way to update the avatar?

### ISSUE THREAD

**Issue by markhorsell** [wesbos/awesome-uses#560]
Looks like its pulled in from twitter and then stays cached? Is there a way to overwrite?

**Comment by markhorsell** [comment]
I see how this works now - service is https://unavatar.now.sh/
Would be nice if avatar could be chosen instead of inferred.

**Comment by Gr8z** [comment]
I was wondering about this too, from the source code, I saw it sends the domain URL to unavatar.now which takes it from yet another service. It is really confusing, it would be nice to know how to change it.

**Comment by iamandrewluca** [comment]
https://gravatar.com/ allows to customize the avatar for a specific email. Can be used as a fallback or somehow.

**Comment by Gr8z** [comment]
I have all my emails registered on Gravatar, but it still doesn't seem to pick it up @iamandrewluca

**Comment by iamandrewluca** [comment]
Gravatar is not used now.
Now are used 2 services

- for caching https://images.weserv.nl
- for avatar retrieve https://unavatar.now.sh

ex: https://images.weserv.nl/?url=https://unavatar.now.sh/markhorsell.com&w=100&l=9&af&il&n=-1

**Comment by Gr8z** [comment]
Looks like unavatar uses clearbit under the hood.

**Comment by wesbos** [comment]
I just modified the code to first use twitter, and then fallback to website URL. With this change, all but 1 person has an avatar. :)

**Comment by wesbos** [comment]
Code here: https://github.com/wesbos/awesome-uses/commit/3c550c57d1c9cd9446e1abbbeeff2692994e07bd

**Comment by iamandrewluca** [comment]
@wesbos lol, I started to search unavatar code how to use fallback twitter or other services, but actually this can be done ))

https://unavatar.now.sh/provider1?fallback=https://unavatar.now.sh/provider2?fallback=https://unavatar.now.sh/provider3?fallback=...

**Comment by wesbos** [comment]
hah yah that is how I did it. I almost opened a PR asking unavatar to add an array of sources, but this is simple enough..

**Comment by sbodi10** [comment]
I noticed that some of the images aren't working anymore (at least for newly added records like mine from Twitter).

https://unavatar.now.sh/twitter/@sbodi10

There's an open issue with [unavatar](https://github.com/Kikobeats/unavatar/issues/121) in which @Kikobeats posted a temporary solution using the [Microlink API](https://github.com/Kikobeats/unavatar/issues/121#issuecomment-748018963)
