### ISSUE TITLE
Change Linux logo from Ubuntu logo to Tux

### ISSUE THREAD

**Issue by duncanjbain** [wesbos/awesome-uses#574]
I’ve noticed that the logo for people using Linux is the Ubuntu logo, perhaps it might be better to change this to Tux the official Linux brand/mascot character.

I feel this will be more representative, who wants an Ubuntu logo when they might be using Arch or Mint? 😬

If this is considered bike shedding then no problem, otherwise I can get a PR put together to make the change :)

**Comment by HugoDF** [comment]
@dunanjbain have you got a link to the correct asset?

**Comment by duncanjbain** [comment]
@HugoDF The best link is probably https://commons.m.wikimedia.org/wiki/File:Tux.svg which had the required attribution etc.

Although I’m not sure how it will look due to the colour of the uses.tech background colour!

**Comment by wesbos** [comment]
ill handle this :)

**Comment by wesbos** [comment]
https://github.com/wesbos/awesome-uses/commit/b8527d9e190dee220b342def8f14c0bce2356fe6

fixed
