### ISSUE TITLE
Merging tags to most common spellings

### ISSUE THREAD

**Issue by maxpou** [wesbos/awesome-uses#637]
hiya,

I just noticed that same filters have been repeated twice or more.

We have: 
* "Front End", "Front end" and "Frontend"
* "Ruby On Rail", "Ruby on Rails" and "Rails" (rails === RoR right?)
* "Gatsby" and "GatsbyJs"
* "Vue" and "VueJS"

Do you mind if I merge people's tags to the most used?

**Comment by HugoDF** [comment]
@maxpou go for it

There was an issue kicking around to deduplicate tags in the code but the agreed upon approach is to edit the data file.

Ideally, make 1 PR per tag that you're unifying.

**Comment by maxpou** [comment]
@HugoDF there you go. As said before, I arbitrary took the most popular keyword
* "Front End", "Front end" and "Frontend" ==> #639
* "Gatsby" and "GatsbyJs" ==> #640 
* "Vue" and "VueJS"  ==> #641

Someone can confirm this? 
* "Ruby On Rail", "Ruby on Rails" and "Rails" (rails === RoR right?)

**Comment by HugoDF** [comment]
> "Ruby On Rail", "Ruby on Rails" and "Rails" (rails === RoR right?)

This is correct, in this case I would use "Ruby on Rails"

**Comment by sam-cross** [comment]
We could list these common spellings at the top of `data.js` so people can easily reference them.

**Comment by nico-bachner** [comment]
Hi,

I've been cleaning up some tags and realised that since it's actually really easy that this issue should perhaps be labelled "good for first-time" or similar.

Would a maintainer be so kind as to do this if they agree?
Cheers

**Comment by nico-bachner** [comment]
I'm planning on merging the VSCode tags next. 

Which spelling is preferrable: Visual Studio Code, VS Code or VSCode ?

**Comment by carbontwelve** [comment]
I can see that this issue has a long history and @BlakeCampbells looks to have made progress in merging tags. Is this issue now completed, or is there work still to do?

**Comment by BlakeCampbells** [comment]
Good call @carbontwelve , I think this is okay to close. 

To keep it from happening in the future we should add either some validation around tags or in `src/util/stats.js` we should make sure `normalizeTags` covers more cases.
