### ISSUE TITLE
Schema in TypeScript for the data?

### ISSUE THREAD

**Issue by rauschma** [wesbos/awesome-uses#661]
It may make sense to create a TypeScript type for `data.js`. Benefits:

* For contributers, it documents what data is allowed where and what properties are available.
* Additionally, it can be used to check the contributed data: https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html

**Comment by HugoDF** [comment]
We've implemented a solution using a schema validator (Joi) + some git magic to only check new entries to data.js, not sure converting to TypeScript will have any benefit.

**Comment by rauschma** [comment]
Nice! Any kind of schema validation will do.

Link to the schema in `data.js` and/or the readme? Then contributors can look it up if they have questions about it.
