### ISSUE TITLE
Add flip-phone to phone list

### ISSUE THREAD

**Issue by binyamin** [wesbos/awesome-uses#765]
I'm thinking about making a `/uses` page. I happen to have a flip phone (yes, I know what year it is). Basically, `phone` in `data.js` requires one of two choices, neither of which apply to me, and the code would break if I didn't put a value.
Concern: What should it be named? Said differently, the words "uses a**n**..." would need to change, since "flip-phone" doesn't start with a vowel.

**Comment by HugoDF** [comment]
@b3u you can edit the list here and submit a PR https://github.com/wesbos/awesome-uses/blob/master/scripts/utils.js#L66

maybe `flip-phone`?

**Comment by nico-bachner** [comment]
Hey @binyamin, I opened a PR that got merged a while back giving `flip-phone` as an option.

Is there anything else in this issue you think still needs to be addressed?

If all is good, perhaps one of the maintainers could close this issue
