### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by mathengedennis** [wesbos/awesome-uses#897]
I cloned the project locally. However, when I run gatsby develop I get the following error message. `SyntaxError: Cannot use import statement outside a module`.

This is related to the import statements inside the file gatsby-node.js.

How do I resolve this?

**Comment by wesbos** [comment]
I think this is because it's a newer version of gatsby. Try change the dev command to this:

https://github.com/wesbos/master-gatsby/blob/master/starter-files/gatsby/package.json#L8-L9

If it works, could you submit a PR to fix it?

**Comment by creativehubspace** [comment]
Unfortunately changing the dev command did not work.

**Comment by HugoDF** [comment]
It's a Babel + Node 12.16+ issue

As far as I understand, Node enabled a modules feature that breaks the non-latest version of Babel

**Comment by wesbos** [comment]
I think it's this: https://github.com/gatsbyjs/gatsby/issues/24925 

The fix I said should work. Will take a look at it sometime soon

**Comment by creativehubspace** [comment]
Running `NODE_OPTIONS='-r esm' gatsby develop` directly works fine.

**Comment by HugoDF** [comment]
Feel free to reopen if you're still running into this issue 😄
